accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup


urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_receipts(request):
    return redirect("home")


urlpatterns = [
    path("", redirect_to_receipts),
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from .views import (
    receipt_list,
    create_receipt,
    category_list,
    account_list,
    create_category,
    create_account,
)


urlpatterns = [
    path("", receipt_list, name="home"),
    path("create/", create_receipt, name="create_receipt"),
    path("categories/", category_list, name="category_list"),
    path("accounts/", account_list, name="account_list"),
    path("categories/create/", create_category, name="create_category"),
    path("accounts/create/", create_account, name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput
    )

receipts/forms.py
from django import forms
from .models import Receipt, ExpenseCategory, Account


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]


class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, SignupForm
from django.views.generic import View
from django.urls import reverse_lazy
from django.contrib.auth.models import User


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LoginForm()
    content = {
        "form": form,
    }
    return render(request, "accounts/login.html", content)


class logout_view(View):
    def get(self, request):
        logout(request)
        return redirect(reverse_lazy("login"))


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                )
                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "the passwords do not match")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from .models import Receipt, ExpenseCategory, Account
from .forms import ReceiptForm, ExpenseCategoryForm, AccountForm
from django.contrib.auth.decorators import login_required


@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {"receipts": receipts}
    return render(request, "receipts/receipt_list.html", context)


@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
    context = {"form": form}
    return render(request, "receipts/create_receipt.html", context)


@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    context = {"categories": categories}
    return render(request, "receipts/categories.html", context)


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    context = {"accounts": accounts}
    return render(request, "receipts/accounts.html", context)


@login_required
def create_category(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.owner = request.user
            category.save()
            return redirect("category_list")
    else:
        form = ExpenseCategoryForm()
    context = {"form": form}
    return render(request, "receipts/create_category.html", context)


@login_required
def create_account(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect("account_list")
    else:
        form = AccountForm()
    context = {"form": form}
    return render(request, "receipts/create_account.html", context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div>
    <h1>Login</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Login</button>
    </form>
  </div>
</main>
{% endblock %}

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Spend Manager{% endblock %}</title>
</head>
    <body>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Receipts</a></li>
                <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
                <li><a href="{% url 'category_list' %}">Expense Categories</a></li>
                <li><a href="{% url 'create_category' %}">Create Expense Category</a></li>
                <li><a href="{% url 'account_list' %}">Accounts</a></li>
                <li><a href="{% url 'create_account' %}">Create Account</a></li>
            </ul>
          </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

receipts/templates/receipts/accounts.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container">
        <h1>Accounts</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                    <tr>
                        <td>{{ account.name }}</td>
                        <td>{{ account.number }}</td>
                        <td>{{ account.receipt_set.count }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">No accounts yet.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

receipts/templates/receipts/categories.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container">
        <h1>Expense Categories</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>{{ category.receipt_set.count }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">No expense categories yet.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

receipts/templates/receipts/create_account.html
{% extends "base.html" %}


{% block content %}
<main>
  <div class="container">
    <h1 class="text-center mb-4">Create Account</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
  </div>
</main>
{% endblock %}

receipts/templates/receipts/create_category.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="container">
    <h1 class="text-center mb-4">Create Category</h1>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Create</button>
        </form>
  </div>
</main>
{% endblock %}

receipts/templates/receipts/create_receipt.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container">
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock %}

receipts/templates/receipts/receipt_list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>My Receipts</h1>
    <table>
        <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
        </thead>
        <tbody>
        {% for receipt in receipts %}
            <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date|date:"m/d/y" }}</td>
            <td>{{ receipt.category.name }}</td>
            <td>{{ receipt.account.name }}</td>
            </tr>
        {% empty %}
            <tr>
            <td colspan="6">No receipts found.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</main>
{% endblock %}